LOGFILE=~/bash_boost.log

echo -e "--- Attempting to boost your bash..." > $LOGFILE

echo -e "bash_profile...\c" >> $LOGFILE

echo -e "bashrc...\c" >> $LOGFILE
source ~/.bashrc

echo -e "version control boost...\c" >> $LOGFILE
source ~/.bash_boost/bash_vcs.sh

echo -e "custom prompt...\c" >> $LOGFILE
source ~/.bash_boost/profile_prompt.sh

echo -e "rvm boost...\c" >> $LOGFILE
source ~/.bash_boost/bash_rvm.sh

echo -e "aliases...\c" >> $LOGFILE
source ~/.aliases

echo -e "cd command boost...\c" >> $LOGFILE
source ~/.bash_boost/cdargs-bash.sh
source ~/.bash_boost/cdargs.sh

echo -e "history boost...\c" >> $LOGFILE
source ~/.history

echo -e "terminal_colors...\c" >> $LOGFILE
source ~/.bash_boost/terminal_colors

echo -e "environment...\c" >> $LOGFILE
source ~/.os_specific/environment

echo -e "emacs_server...\c" >> $LOGFILE
source ~/.bash_boost/emacs_server

echo -e "paths..." >> $LOGFILE
source ~/.os_specific/paths

echo -e "java functions..." >> $LOGFILE
source ~/.bash_boost/java_functions.sh

echo -e "user specific boost..." >> $LOGFILE
source ~/.user_specific/loader

# echo "--- Boost process Successful and Complete! (details logged to $LOGFILE)"

##
# Your previous /Users/nfrausto/.bash_profile file was backed up as /Users/nfrausto/.bash_profile.macports-saved_2014-09-15_at_12:35:19
##

# MacPorts Installer addition on 2014-09-15_at_12:35:19: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.


[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
